baseURL: "https://emilmirzayev.github.io" 
title: Emil Mirzayev
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Interviews
          url: interviews/
          weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "testestest"
    author: Emil Mirzayev
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses", "interviews"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    ignoreLogs: ['warning-partial-superfluous-prefix']
    profileMode:
          enabled: true
          title: Dr. Emil Mirzayev
          subtitle: "Welcome to my personal website! I am a post-doctoral researcher at Strategy and Entrepreneurship department at University College London School of Management.<br> <br> My research focuses on leveraging **generative AI**, particularly **large language models**, to enhance **strategic decision-making processes**. <br> <br> **I am on 2025/2026 job market**. <br> <br> Outside academia, I am a co-founder of the Azerbaijani Python User Group. I strongly support the availability of educational materials in the Azerbaijani language and, therefore, have given dozens of free webinars on the topics of Python, AI, and Data Science in Azerbaijani. <br> <br> When stepping away from research and community work, I enjoy engaging my mind with strategy games, reading sci-fi, cooking and very long walks. <br> <br>"
          imageUrl: "EMprofilePicture2.JPG"
          imageWidth: 270
          imageHeight: 250
          buttons:
            - name: Job Market Paper
              url: paper/JMP.html
            - name: Papers
              url: papers/
            - name: Intreviews
              url: interviews/

            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:emilbmirzayev@gmail.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=5B197WgAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/emilmirzayev
        - name: Twitter
          url: https://x.com/MirzayevEmil
        - name: LinkedIn
          url: https://www.linkedin.com/in/emilmirzayev/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Emil Mirzayev"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2